#!/bin/bash
# This is a fork of the original cronic (Ref below)
# Check README.md in https://github.com/shadiakiki1986/cronic2 for more details
#
# The original cronic:
#   http://habilis.net/cronic/
#   Cronic v2 - cron job report wrapper
#   Copyright 2007 Chuck Houpt. No rights reserved, whatsoever.
#   Public Domain CC0: http://creativecommons.org/publicdomain/zero/1.0/

set -eu

OUT=/tmp/cronic.out.$$
ERR=/tmp/cronic.err.$$
TRACE=/tmp/cronic.trace.$$
NOTIF=~/.cronic2.db
CMND=`echo $@`

set +e
"$@" >$OUT 2>$TRACE
RESULT=$?
set -e

PATTERN="^${PS4:0:1}\\+${PS4:1}"
if grep -aq "$PATTERN" $TRACE
then
    ! grep -av "$PATTERN" $TRACE > $ERR
else
    ERR=$TRACE
fi

if [ $RESULT -ne 0 -o -s "$ERR" ]
    then

    if [ ! -e "$NOTIF" ] || ! grep -aq "$CMND" $NOTIF
    then
        echo "Cronic detected failure or error output for the command:"
        echo "$@"
        echo
        echo "RESULT CODE: $RESULT"
        echo
        echo "ERROR OUTPUT:"
        cat "$ERR"
        echo
        echo "STANDARD OUTPUT:"
        cat "$OUT"
        if [ $TRACE != $ERR ]
        then
            echo
            echo "TRACE-ERROR OUTPUT:"
            cat "$TRACE"
        fi

        # store in NOTIF file to avoid re-notification
        if [ ! -e "$NOTIF" ]
        then
          echo $CMND
        else
          echo $CMND >> $NOTIF
        fi
    fi
else
    if [ -e "$NOTIF" ] && grep -aq "$CMND" $NOTIF
    then
        # drop the entry from $NOTIF
        # The || is needed for the case where the error is the last error in the file, and grep -av returns an empty result
        ( grep -av "$CMND" "$NOTIF" > ${NOTIF}.tmp && mv ${NOTIF}.tmp "$NOTIF" ) || ( rm ${NOTIF} && touch ${NOTIF} && rm ${NOTIF}.tmp )
    fi
fi

rm -f "$OUT"
rm -f "$ERR"
rm -f "$TRACE"
